### ISSUE TITLE
PS4 Component not working on Hass 0.52.1

### ISSUE THREAD

**Issue by outrun0506** [hmn/home-assistant-config#11]
Hi,

as mentioned here:

https://community.home-assistant.io/t/playstation-4-ps4-custom-component/16974/64?u=outrun

I'm having troubles using your PS4 Custom Component

Hass-LOG:

```
2017-08-30 18:56:05 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform ps4
Traceback (most recent call last):
  File "/home/hass/.homeassistant/custom_components/media_player/ps4.py", line 336, in search
    data = json.loads(value)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

Any Tipps whats going wrong?

Thanks in advanced

Br

Lukas

**Comment by outrun0506** [comment]
Fixed it myself. Just reinstalled ps4-waker on my pi
