### ISSUE TITLE
On/off not working

### ISSUE THREAD

**Issue by glassbase** [hmn/home-assistant-config#22]
Just switched from official HA docker to yours with the included ps4-waker. 

I created my credentials file and copied it into my /config/ directory. I specified it in my ps4 media_player section as the correct file name.  

PS4 does not turn on or off. My games list loads and it updates the json file. 

And for some odd reason, the Playstation 4 configurator comes up. I have tried copying the contents of the credentials file into the configurator box, that didn't work and it changes the layout of the file. 

I can run these and PS4 wakes and sleeps.
```
docker exec -it hass ps4-waker -c /config/.ps4-wake.credentials.json
docker exec -it hass ps4-waker -c /config/.ps4-wake.credentials.json standby
```

This person is basically having same issue:
https://community.home-assistant.io/t/playstation-4-ps4-custom-component/16974/114

I use cmdSwitch2 with ps4-waker with Homebridge and it works fine as well.

**Comment by glassbase** [comment]
Here is logged error in docker log
```
2018-02-19 23:30:20 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1519101020.2313352, level=ERROR, message=Error executing service <ServiceCall media_player.turn_off: entity_id=['media_player.ps4']>, exception=Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/media_player/__init__.py", line 403, in async_service_handler
    yield from getattr(player, method['method'])(**params)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/ps4.py", line 357, in turn_off
    self.ps4.standby()
  File "/config/deps/lib/python3.6/site-packages/pyps4/ps4.py", line 90, in standby
    self._connection.login()
  File "/config/deps/lib/python3.6/site-packages/pyps4/connection.py", line 63, in login
    self._send_login_request()
  File "/config/deps/lib/python3.6/site-packages/pyps4/connection.py", line 160, in _send_login_request
    'account_id': self._credential.encode().ljust(64, b'\x00'),
AttributeError: 'dict' object has no attribute 'encode'
, source=deps/lib/python3.6/site-packages/pyps4/connection.py>
```

**Comment by hmn** [comment]
we are working on a new python only module so it can be added to the official repo, but there are some problems at the moment.

**Comment by glassbase** [comment]
I figured it out. I think the setup has changed since the wiki was wrote. 

When I got the Configurator I entered only the credentials string from the json file and not the entire PS4-waker json string

Thanks
