### ISSUE TITLE
Cryptodome

### ISSUE THREAD

**Issue by tjakie** [hmn/home-assistant-config#23]
I'm running on ubuntu and I got the following error in my log:

I tried installing cryptodome as follwing:
$ sudo apt-get install build-essential libgmp3-dev python3-dev
$ pip install pycryptodomex
$ python3 -m Cryptodome.SelfTest
-> after this command the same error occurs.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/configurator.py", line 224, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sjaak/.homeassistant/custom_components/media_player/ps4.py", line 115, in ps4_configuration_callback
    if _check_ps4(host, credentials):
  File "/home/sjaak/.homeassistant/custom_components/media_player/ps4.py", line 60, in _check_ps4
    import pyps4
  File "/home/sjaak/.homeassistant/deps/lib/python3.5/site-packages/pyps4/__init__.py", line 2, in <module>
    from .connection import *
  File "/home/sjaak/.homeassistant/deps/lib/python3.5/site-packages/pyps4/connection.py", line 9, in <module>
    from Cryptodome.Cipher import AES, PKCS1_OAEP
ImportError: No module named 'Cryptodome'

Please help:)

**Comment by tjakie** [comment]
I found thes sollution here: https://home-assistant.io/developers/component_deps_and_reqs/
It needed to be installed in this way: pip install pycryptodomex --target ~/.homeassistant/deps
