### ISSUE TITLE
'Ps4' object has no attribute 'remote'

### ISSUE THREAD

**Issue by tringler** [hmn/home-assistant-config#24]
Hello,

I get `'Ps4' object has no attribute 'remote'` if I try i.e. example to switch off the PS4 by the custom_component.

```
2018-03-05 21:53:14 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall media_player.media_play_pause: entity_id=['media_player.livingroom_ps4']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/media_player/__init__.py", line 402, in async_service_handler
    yield from getattr(player, method['method'])(**params)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/media_player/ps4.py", line 371, in media_pause
    self.ps4.remote('ps')
AttributeError: 'Ps4' object has no attribute 'remote'
```

`ps4-waker -c .ps4-wake.credentials.json -d 10.10.10.221 standby` works.

**Comment by hmn** [comment]
it has been added to the python module
